//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnayatovHouseholdService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long commentID { get; set; }
        public string message { get; set; }
        public long masterID { get; set; }
        public long requestsID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
