//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnayatovHouseholdService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public long requestID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public long homeTechTypeId { get; set; }
        public string homeTechModel { get; set; }
        public string problemDescryption { get; set; }
        public long requestStatusId { get; set; }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<long> masterID { get; set; }
        public long clientID { get; set; }
    
        public virtual HomeTechTypes HomeTechTypes { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual RequestStatuses RequestStatuses { get; set; }
    }
}
